spring.application.name=trendyol
spring.datasource.url=jdbc:mysql://localhost:3306/siparis_islem?useUnicode=true&characterEncoding=UTF-8
spring.datasource.username=kisi_new
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
